### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Lola",
  "email": "lola@mail.com",
  "password": "password",
  "password_confirmation": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "tay@mail.com",
  "password": "password"
}


### Users show
GET  http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE1NjU3OTF9.s8369qg7hm2i3DQXjGpfkte5SXH8jlUog3J4UNfnCO8